// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcY-urrlgEbOqcUBk4sCxg0n2vHV2jKfE',
    appId: '1:349096357661:web:3a87ab455d2e0e8c6ebbf4',
    messagingSenderId: '349096357661',
    projectId: 'tugaspab2noval',
    authDomain: 'tugaspab2noval.firebaseapp.com',
    databaseURL: 'https://tugaspab2noval-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugaspab2noval.firebasestorage.app',
    measurementId: 'G-82QNGVQKH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGIOx0dD_jW52g4X8NXwGRa3-acugSaI',
    appId: '1:349096357661:android:2f05f6ce547903ee6ebbf4',
    messagingSenderId: '349096357661',
    projectId: 'tugaspab2noval',
    databaseURL: 'https://tugaspab2noval-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugaspab2noval.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5GbQivWQL-H3gAWZ-39DFjGM0dEtRbrc',
    appId: '1:349096357661:ios:57860c969f4006096ebbf4',
    messagingSenderId: '349096357661',
    projectId: 'tugaspab2noval',
    databaseURL: 'https://tugaspab2noval-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugaspab2noval.firebasestorage.app',
    iosBundleId: 'com.example.tugaspab2noval',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5GbQivWQL-H3gAWZ-39DFjGM0dEtRbrc',
    appId: '1:349096357661:ios:57860c969f4006096ebbf4',
    messagingSenderId: '349096357661',
    projectId: 'tugaspab2noval',
    databaseURL: 'https://tugaspab2noval-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugaspab2noval.firebasestorage.app',
    iosBundleId: 'com.example.tugaspab2noval',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcY-urrlgEbOqcUBk4sCxg0n2vHV2jKfE',
    appId: '1:349096357661:web:844c2118797457a96ebbf4',
    messagingSenderId: '349096357661',
    projectId: 'tugaspab2noval',
    authDomain: 'tugaspab2noval.firebaseapp.com',
    databaseURL: 'https://tugaspab2noval-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugaspab2noval.firebasestorage.app',
    measurementId: 'G-3D7H3GP579',
  );

}